[32m2024-08-20 00:54:08 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 666da218-90ce-4a35-be68-1f9607453da4 - 450627 - LOGS_CAPTURED - Started capturing logs in process (pid: 450627).
[32m2024-08-20 00:54:08 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 666da218-90ce-4a35-be68-1f9607453da4 - 450627 - predict_data - STEP_START - Started execution of step "predict_data".
00:54:08 - cmdstanpy - INFO - Chain [1] start processing
00:54:08 - cmdstanpy - INFO - Chain [1] done processing
/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/prophet/plot.py:72: FutureWarning: The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result
  fcst_t = fcst['ds'].dt.to_pydatetime()
/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/prophet/plot.py:73: FutureWarning: The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result
  ax.plot(m.history['ds'].dt.to_pydatetime(), m.history['y'], 'k.',
[32m2024-08-20 00:54:09 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 666da218-90ce-4a35-be68-1f9607453da4 - 450627 - predict_data - STEP_FAILURE - Execution of step "predict_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "predict_data"::

ValueError: 
The fig parameter must be a dict or Figure.
    Received value of type <class 'matplotlib.figure.Figure'>: Figure(1000x600)

Stack Trace:
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 474, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspace/pranatics/sources/pipeline/hedera_pipeline/hedera_pipeline/assets.py", line 129, in predict_data
    pio.write_image(fig, CRYPTO_TRANSFER_PREDICTION_PLOT_FILE)
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 266, in write_image
    img_data = to_image(
               ^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/plotly/io/_kaleido.py", line 142, in to_image
    fig_dict = validate_coerce_fig_to_dict(fig, validate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/poetry/virtualenvs/pipeline-z_B504z3-py3.12/lib/python3.12/site-packages/plotly/io/_utils.py", line 20, in validate_coerce_fig_to_dict
    raise ValueError(
[0m
